# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: jumpness_test1_development
  host: 127.0.0.1
  username: root
  
test:
  adapter: mysql2
  database: jumpness_test1_development
  host: 127.0.0.1
  username: root
  
production:
  adapter: mysql2
  database: jumpness_test1_development
  host: 127.0.0.1
  username: root
