$(document).ready ->
	try
		michigan_cities = ["Ada",
		"Addison",
		"Adrian",
		"Ahmeek",
		"Akron",
		"Alanson",
		"Albion",
		"Algonac",
		"Allegan",
		"Allen",
		"Allen Park",
		"Allendale",
		"Alma",
		"Almont",
		"Alpena",
		"Alpha",
		"Ann Arbor",
		"Applegate",
		"Argyle",
		"Armada",
		"Ashley",
		"Athens",
		"Atlanta",
		"Auburn",
		"Auburn Hills",
		"Au Gres",
		"Au Sable",
		"Augusta",
		"Bad Axe",
		"Baldwin",
		"Bancroft",
		"Bangor",
		"Bannister",
		"Baraga",
		"Baroda",
		"Barryton",
		"Barton Hills Village",
		"Battle Creek",
		"Bay City",
		"Bay Port",
		"Bear Lake",
		"Beaverton",
		"Belding",
		"Bellaire",
		"Belleville",
		"Bellevue",
		"Benton Harbor",
		"Benzonia",
		"Berkley",
		"Berrien Springs",
		"Bessemer",
		"Beulah",
		"Beverly Hills",
		"Big Rapids",
		"Bingham Farms",
		"Birch Run",
		"Birmingham",
		"Blissfield",
		"Bloomfield Hills",
		"Bloomingdale",
		"Boon",
		"Boyne City",
		"Boyne Falls",
		"Breckenridge",
		"Breedsville",
		"Bridgman",
		"Brighton",
		"Britton",
		"Bronson",
		"Brooklyn",
		"Brown City",
		"Buchanan",
		"Buckley",
		"Burlington",
		"Burr Oak",
		"Burton",
		"Byron",
		"Cadillac",
		"Caledonia",
		"Calumet",
		"Camden",
		"Capac",
		"Carleton",
		"Carney",
		"Caro",
		"Carson City",
		"Carsonville",
		"Caseville",
		"Casnovia",
		"Caspian",
		"Cass City",
		"Cassopolis",
		"Cedar Springs",
		"Cement City",
		"Center Line",
		"Central Lake",
		"Centreville",
		"Charlevoix",
		"Charlotte",
		"Champion",
		"Chatham",
		"Cheboygan",
		"Chelsea",
		"Chesaning",
		"Clare",
		"Clarkston",
		"Clarksville",
		"Clawson",
		"Clayton",
		"Clifford",
		"Climax",
		"Clinton",
		"Clio",
		"Coldwater",
		"Coleman",
		"Coloma",
		"Colon",
		"Columbiaville",
		"Comstock Park",
		"Concord",
		"Constantine",
		"Coopersville",
		"Copemish",
		"Copper City",
		"Coral",
		"Corunna",
		"Croswell",
		"Crystal Falls",
		"Custer",
		"Daggett",
		"Dansville",
		"Davison",
		"Dearborn",
		"Dearborn Heights",
		"Decatur",
		"Decker",
		"Deckerville",
		"Deerfield",
		"DeTour Village",
		"Detroit",
		"DeWitt",
		"Dexter",
		"Dimondale",
		"Douglas",
		"Dowagiac",
		"Dryden",
		"Dublin",
		"Dundee",
		"Durand",
		"Eagle",
		"East Grand Rapids",
		"East Jordan",
		"East Lake",
		"East Lansing",
		"Eastpointe",
		"East Tawas",
		"Eaton Rapids",
		"Eau Claire",
		"Ecorse",
		"Edmore",
		"Edwardsburg",
		"Elberta",
		"Elk Rapids",
		"Elkton",
		"Ellsworth",
		"Elsie",
		"Emmett",
		"Empire",
		"Escanaba",
		"Essexville",
		"Estral Beach",
		"Evart",
		"Fairgrove",
		"Falmouth",
		"Farmington",
		"Farmington Hills",
		"Farwell",
		"Fennville",
		"Fenton",
		"Ferndale",
		"Ferrysburg",
		"Fife Lake",
		"Filer City",
		"Flat Rock",
		"Flint",
		"Flushing",
		"Forestville",
		"Fountain",
		"Fowler",
		"Fowlerville",
		"Frankenmuth",
		"Frankfort",
		"Franklin",
		"Fraser",
		"Freeport",
		"Free Soil",
		"Fremont",
		"Fruitport",
		"Gaastra",
		"Gagetown",
		"Gaines",
		"Galesburg",
		"Galien",
		"Garden",
		"Garden City",
		"Gaylord",
		"Gibraltar",
		"Gladstone",
		"Gladwin",
		"Glen Arbor",
		"Gobles",
		"Goodrich",
		"Grand Beach",
		"Grand Blanc",
		"Grand Haven",
		"Grand Ledge",
		"Grand Rapids",
		"Grandville",
		"Grant",
		"Grass Lake",
		"Grayling",
		"Greenville",
		"Grosse Pointe",
		"Grosse Pointe Farms",
		"Grosse Pointe Park",
		"Grosse Pointe Shores",
		"Grosse Pointe Woods",
		"Hamilton, Village",
		"Hale",
		"Hamtramck",
		"Hancock",
		"Hanover",
		"Harbert",
		"Harbor Beach	Harbor Springs",
		"Harper Woods",
		"Harrietta",
		"Harrison",
		"Harrisville",
		"Hart",
		"Hartford",
		"Hastings",
		"Hawkins",
		"Hazel Park",
		"Hesperia",
		"Hersey",
		"Highland Park",
		"Hillman",
		"Hillsdale",
		"Holland",
		"Holly",
		"Holt",
		"Homer",
		"Honor",
		"Hopkins",
		"Houghton",
		"Houghton Lake",
		"Howard City",
		"Howell",
		"Hubbard Lake",
		"Hubbardston",
		"Hudson",
		"Hudsonville",
		"Huntington Woods",
		"Imlay City",
		"Indian River",
		"Inkster",
		"Ionia",
		"Iron Mountain",
		"Iron River",
		"Ironwood",
		"Ishpeming",
		"Ithaca",
		"Jackson",
		"Jonesville",
		"Kalamazoo",
		"Kaleva",
		"Kalkaska",
		"Keego Harbor",
		"Kent City",
		"Kentwood",
		"Kinde",
		"Kingsford",
		"Kingsley",
		"Kingston",
		"Laingsburg",
		"Lake Angelus",
		"Lake Ann",
		"Lake City",
		"Lake Leelanau",
		"Lake Linden",
		"Lake Odessa",
		"Lake Orion",
		"Lakeview",
		"Lakewood",
		"Lakewood Club",
		"L'Anse",
		"Langston",
		"Lansing",
		"Lapeer",
		"Lathrup Village",
		"Laurium",
		"Lawrence",
		"Lawton",
		"Lennon",
		"Leonard",
		"LeRoy",
		"Leslie",
		"Lewiston",
		"Lexington",
		"Lincoln",
		"Lincoln Park",
		"Linden",
		"Litchfield",
		"Livonia",
		"Lowell",
		"Lucas",
		"Ludington",
		"Luna Pier",
		"Luther",
		"Lyons",
		"Mackinac Island",
		"Mackinaw City",
		"Madison Heights",
		"Mancelona",
		"Manchester",
		"Manistee",
		"Manistique",
		"Manton",
		"Maple City",
		"Maple Rapids",
		"Marcellus",
		"Marine City",
		"Marion",
		"Marlette",
		"Marquette",
		"Marshall",
		"Martin",
		"Marysville",
		"Mason",
		"Mattawan",
		"Maybee",
		"Mayville",
		"McBain",
		"McBride",
		"Mecosta",
		"Melvin",
		"Melvindale",
		"Memphis",
		"Mendon",
		"Menominee",
		"Merrill	Merritt",
		"Mesick ",
		"Metamora",
		"Michiana",
		"Middleton",
		"Middleville",
		"Midland",
		"Milan",
		"Milford",
		"Millersburg",
		"Millington",
		"Minden",
		"Mineral Hills",
		"Mio",
		"Moddersville",
		"Monroe",
		"Montague",
		"Montgomery",
		"Montrose",
		"Moorestown",
		"Morenci",
		"Morley",
		"Morrice",
		"Mount Clemens",
		"Mount Morris",
		"Mount Pleasant",
		"Muir",
		"Mulliken",
		"Munising",
		"Muskegon",
		"Muskegon Heights",
		"Nashville",
		"Negaunee",
		"Newaygo",
		"New Baltimore",
		"Newberry",
		"New Buffalo",
		"New Era",
		"New Haven",
		"New Lothrop",
		"Niles",
		"North Adams",
		"North Branch",
		"North Muskegon",
		"Northport",
		"Northville",
		"Norton Shores",
		"Norway",
		"Norwood",
		"Novi",
		"Oakley",
		"Oak Park",
		"Olivet",
		"Omena",
		"Omer",
		"Onaway",
		"Onekama",
		"Onsted",
		"Ontanogan",
		"Orchard Lake",
		"Ortonville",
		"Oscoda",
		"Otisville",
		"Otsego",
		"Otter Lake",
		"Ovid",
		"Owendale",
		"Owosso",
		"Oxford",
		"Parchment",
		"Paris",
		"Parma",
		"Paw Paw",
		"Peck",
		"Pellston",
		"Pentwater",
		"Perrinton",
		"Perry",
		"Petersburg",
		"Petoskey",
		"Pewamo",
		"Pierson",
		"Pigeon",
		"Pinckney",
		"Pinconning",
		"Plainwell",
		"Pleasant Ridge",
		"Plymouth",
		"Pontiac",
		"Portage",
		"Port Austin",
		"Port Hope",
		"Port Huron",
		"Portland",
		"Port Sanilac",
		"Posen",
		"Potterville",
		"Powers",
		"Prescott",
		"Prudenville",
		"Quincy",
		"Ravenna",
		"Reading",
		"Reed City",
		"Reese",
		"Remus",
		"Richland",
		"Richmond",
		"Riverdale",
		"River Rouge",
		"Riverview",
		"Rochester",
		"Rochester Hills",
		"Rockford",
		"Rockwood",
		"Rogers City",
		"Romeo",
		"Romulus	Roosevelt Park",
		"Roscommon",
		"Rosebush",
		"Rose City",
		"Roseville",
		"Rothbury",
		"Royal Oak",
		"Saginaw",
		"Saint Charles",
		"Saint Clair",
		"Saint Clair Shores",
		"Saint Helen (St. Helens)",
		"Saint Ignace",
		"Saint Johns",
		"Saint Joseph",
		"Saint Louis",
		"Saline",
		"Sand Lake",
		"Sand Point",
		"Sandusky",
		"Sanford",
		"Saranac",
		"Saugatuck",
		"Sault Sainte Marie",
		"Schoolcraft",
		"Scottville",
		"Sebewaing",
		"Shabbona",
		"Shelby",
		"Shepherd",
		"Sheridan",
		"Sherwood",
		"Shoreham",
		"Sidney",
		"Six Lakes",
		"Southfield",
		"Southgate",
		"South Haven",
		"South Lyon",
		"South Range",
		"South Rockwood",
		"Sparta",
		"Springfield",
		"Spring Lake",
		"Springport",
		"Stambaugh",
		"Standish",
		"Stanton",
		"Stanwood",
		"Stephenson",
		"Sterling",
		"Sterling Heights",
		"Stevensville",
		"Stockbridge",
		"Stronach",
		"Sturgis",
		"Sunfield",
		"Suttons Bay",
		"Swartz Creek",
		"Sylvan Lake",
		"Tawas City",
		"Taylor",
		"Tecumseh",
		"Tekonsha",
		"Thompsonville",
		"Three Oaks",
		"Three Rivers",
		"Traverse City",
		"Trenton",
		"Troy",
		"Trufant",
		"Turner",
		"Tustin",
		"Twining",
		"Ubly",
		"Union City",
		"Unionville",
		"Utica",
		"Vandalia",
		"Vanderbilt",
		"Vassar",
		"Vermontville",
		"Vernon",
		"Vestaburg",
		"Vicksburg",
		"Wakefield",
		"Waldron",
		"Walker",
		"Walkerville",
		"Walled Lake",
		"Walloon Lake",
		"Warren",
		"Watervliet",
		"Wayland",
		"Wayne",
		"Webberville",
		"Wellston",
		"West Branch",
		"Westland",
		"Westphalia",
		"White Cloud",
		"Whitehall",
		"White Pigeon",
		"Whitmore Lake",
		"Whittemore",
		"Williamston",
		"Wixom",
		"Wolverine",
		"Wolverine Lake",
		"Woodhaven",
		"Woodland",
		"Wyandotte",
		"Wyoming",
		"Yale",
		"Ypsilanti",
		"Zeeland",
		"Zilwaukee"]
		$('input#citystate').autocomplete {source: michigan_cities, select: (event,ui)->
			$('.step1').hide('slow')
			$('.step2').show("bounce", {times:3}, 300)
			$('.step3').hide(0)
			$('.step4').hide(0)
			
		}
		
		$('input#citystate').keydown (event)->
			if event.keyCode != 13
				$('.step1').show('slow')
				$('.step2').hide(0)
				$('.step3').hide(0)
				$('.step4').hide(0)
				
			return event.keyCode != 13
		
		$("#date-div").datepicker(
			defaultDate: "+1w"
			minDate: 2
			maxDate: "+3M"
			changeMonth: false
			numberOfMonths: 3
			showAnim: "bounce"
			altField: "#date"
			altFormat: "DD, d MM, yy"
			onSelect: (dateText, inst) ->
				$('.step2').hide("bounce", {times:5}, 200, ()->
					$('.step3').fadeIn('slow')
					$('.step4').fadeIn('slow')
					
				)
		)
		
		$("#date").click (event)->
			$('.step2').show("bounce", {times:3}, 300)
			$('.step3').hide(0)
			$('.step4').hide(0)
			
			
		$("#from, #to").timepicker(
			ampm: true
			hourMin: 8
			hourMax: 20
			stepMinute: 15
			showAnim: "bounce"
		)
	catch e
		alert(e)

